-- Run as MAGNET. MyMagnet's SQLite schema (DB_SCHEMA in magnetlookup.py and
-- _DB_SCHEMA in webserver.py, identical) translated to Oracle 23ai/26ai.
--
-- Translation choices, so the app patch stays small:
--  * Timestamps stay as ISO-8601 strings (VARCHAR2), as in SQLite. The app
--    writes datetime.isoformat() and sorts on the text; changing to
--    TIMESTAMP would touch every read path for no gain in this lab.
--  * INTEGER PRIMARY KEY AUTOINCREMENT -> identity column, BY DEFAULT ON
--    NULL so the one-time migration can insert the existing SQLite ids.
--  * Integers are NUMBER(p) with scale 0, which python-oracledb returns as
--    Python int (a bare NUMBER can come back as float).
--  * torrents.size -> torrent_size. SIZE is on Oracle's SQL reserved-words
--    list (verified), so it can't be an unquoted column name. The app
--    aliases it back to "size" in its SELECTs, so the JSON API is unchanged.
--  * magnet is VARCHAR2(32767): magnet URIs with tracker lists can exceed
--    4000 bytes, and ADB defaults to MAX_STRING_SIZE = EXTENDED (verified),
--    which allows 32767. VARCHAR2 rather than CLOB avoids LOB handling in
--    the driver.
--  * New: torrents.title_vec VECTOR(384, FLOAT32), the title embedding.
--    384 matches all-MiniLM-L12-v2's output. Filled by VECTOR_EMBEDDING()
--    on insert (app) or by 04_embeddings_and_index.sql (backfill).
--  * IF NOT EXISTS is 23ai+ syntax; it keeps this script re-runnable the
--    way the SQLite CREATE TABLE IF NOT EXISTS was.
--  * Oracle stores '' as NULL. Every NOT NULL text column gets a non-empty
--    value from the app today; if one ever arrives empty, the insert fails
--    instead of storing ''.

CREATE TABLE IF NOT EXISTS searches (
    id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    run_at        VARCHAR2(32)   NOT NULL,
    terms         VARCHAR2(4000) NOT NULL,
    js_mode       NUMBER(1)  DEFAULT 0 NOT NULL,
    total_found   NUMBER(10) DEFAULT 0 NOT NULL,
    dupes_removed NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS torrents (
    info_hash     VARCHAR2(64)    PRIMARY KEY,
    title         VARCHAR2(4000)  NOT NULL,
    torrent_size  VARCHAR2(64),
    best_seeds    NUMBER(10) DEFAULT 0 NOT NULL,
    best_leeches  NUMBER(10) DEFAULT 0 NOT NULL,
    first_seen    VARCHAR2(32)    NOT NULL,
    last_seen     VARCHAR2(32)    NOT NULL,
    magnet        VARCHAR2(32767) NOT NULL,
    title_vec     VECTOR(384, FLOAT32)
);

CREATE TABLE IF NOT EXISTS torrent_sites (
    info_hash     VARCHAR2(64)  NOT NULL REFERENCES torrents(info_hash),
    site          VARCHAR2(255) NOT NULL,
    PRIMARY KEY (info_hash, site)
);

CREATE TABLE IF NOT EXISTS search_results (
    id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    search_id     NUMBER(19)     NOT NULL REFERENCES searches(id),
    info_hash     VARCHAR2(64)   NOT NULL REFERENCES torrents(info_hash),
    search_term   VARCHAR2(1000) NOT NULL,
    seeds         NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(400) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS search_terms (
    term          VARCHAR2(1000) PRIMARY KEY,
    category      VARCHAR2(400) DEFAULT 'Default' NOT NULL,
    first_used    VARCHAR2(32)  NOT NULL,
    last_used     VARCHAR2(32)  NOT NULL,
    use_count     NUMBER(10) DEFAULT 1 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sr_search  ON search_results(search_id);
CREATE INDEX IF NOT EXISTS idx_sr_term    ON search_results(search_term);
CREATE INDEX IF NOT EXISTS idx_sr_hash    ON search_results(info_hash);
CREATE INDEX IF NOT EXISTS idx_t_seeds    ON torrents(best_seeds DESC);
CREATE INDEX IF NOT EXISTS idx_t_seen     ON torrents(last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_terms_used ON search_terms(last_used DESC);
CREATE INDEX IF NOT EXISTS idx_terms_cat  ON search_terms(category);
